version: "3"
services:
  menudb:
    image: mongo:latest
    ports:
      - "27017:27017"
  menu:
    build: .
    environment:
      WAIT_HOSTS: menudb:27017
    ports:
      - "80:80"
    depends_on:
      - menudb
